export const environment = {
  production: false,
  cesiumToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxNDI5ZDQyOS1kMjQ4LTQ3NDMtYjc4Zi1hNzIxOTI1MDA3NmEiLCJpZCI6NDQzODEzLCJzdWIiOiJBeWRpbiBLYXlhIiwiaXNzIjoiaHR0cHM6Ly9hcGkuY2VzaXVtLmNvbSIsImF1ZCI6InB1YmxpYyIsImlhdCI6MTc4MTQzMDA3NH0.MZk1CgcIg7GkjbB70GscNtXSPqEjTOTaeYw39Zzdfr8'

};